# Analysis of insights of the district

In [8]:
import geopandas as gpd
import pandas as pd

In [9]:
df= pd.read_csv("../data/mart/walkability_data_mart.csv", sep=",")

In [10]:
df.columns

Index(['district', 'pt_stops', 'crossings', 'stadtrad', 'emobility', 'lsa',
       'green_area_m2', 'street_segments', 'bike_km', 'Berichtsjahr_Jahr',
       'population', 'children', 'elderly'],
      dtype='str')

In [11]:
# --- KPIs berechnen ---
df["stops_per_1000"] = df["pt_stops"] / df["population"] * 1000
df["crossings_per_1000"] = df["crossings"] / df["population"] * 1000
df["bike_km_per_1000"] = df["bike_km"] / df["population"] * 1000
df["green_per_person"] = df["green_area_m2"] / df["population"]

# --- Prozentwerte ---
df["elderly_share"] = df["elderly"] / df["population"] * 100
df["children_share"] = df["children"] / df["population"] * 100

# --- Runden (für saubere Darstellung) ---
df["stops_per_1000"] = df["stops_per_1000"].round(3)
df["crossings_per_1000"] = df["crossings_per_1000"].round(3)
df["bike_km_per_1000"] = df["bike_km_per_1000"].round(3)
df["green_per_person"] = df["green_per_person"].round(2)
df["elderly_share"] = df["elderly_share"].round(1)
df["children_share"] = df["children_share"].round(1)

# --- Kontrolle ---
df[[
    "stops_per_1000",
    "crossings_per_1000",
    "bike_km_per_1000",
    "green_per_person",
    "elderly_share",
    "children_share"
]]

,stops_per_1000,crossings_per_1000,bike_km_per_1000,green_per_person,elderly_share,children_share
0,0.512,0.404,0.325,8.4,13.6,11.0

In [16]:

df.to_csv(
    "../data/mart/walkability_data_mart.csv",
    index=False,
    sep=";",              # wichtig für DE Systeme
    decimal=","           # 🔥 entscheidend!
)

In [17]:

df.to_csv(
    "../data/mart/walkability_data_mart_v2.csv",
    index=False,
    sep=";",              # wichtig für DE Systeme
    decimal=","           # 🔥 entscheidend!
)

In [13]:
df.dtypes

district                  str
pt_stops                int64
crossings               int64
stadtrad                int64
emobility               int64
lsa                     int64
green_area_m2         float64
street_segments         int64
bike_km               float64
Berichtsjahr_Jahr       int64
population              int64
children                int64
elderly                 int64
stops_per_1000        float64
crossings_per_1000    float64
bike_km_per_1000      float64
green_per_person      float64
elderly_share         float64
children_share        float64
dtype: object

In [14]:
df.head()

,district,pt_stops,crossings,stadtrad,emobility,lsa,green_area_m2,street_segments,bike_km,Berichtsjahr_Jahr,population,children,elderly,stops_per_1000,crossings_per_1000,bike_km_per_1000,green_per_person,elderly_share,children_share
0,Barmbek-Süd,19,15,10,20,27,311652.0,520,12.042108,2024,37091,4096,5057,0.512,0.404,0.325,8.4,13.6,11.0